services:
  db:
    image: mysql:8.0
    container_name: tcmb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: AyranGelistirme2002!
      MYSQL_DATABASE: tcmb_exchange_rates
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout : 5s
    networks:
      - tcmb_network

  dataapi:
    build: ./provision-Project-DataApi
    container_name: tcmb_dataapi
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:80"  # HTTP
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=tcmb_exchange_rates;User=root;Password=AyranGelistirme2002!;
    command:
      - sh -c "dotnet ef database update && dotnet run"
    networks:
      - tcmb_network

  businessapi:
    build: ./provision-Project-BusinessApi
    container_name: tcmb_businessapi
    restart: always
    ports:
      - "5002:80"  # HTTP
    depends_on:
        - dataapi
    networks:
      - tcmb_network

  currencywebsite:
    build: ./provision-Project-CurrencyWebsite
    container_name: tcmb_currencywebsite
    ports:
      - "5004:80" # HTTP
    depends_on:
      - dataapi
      - businessapi
    networks:
      - tcmb_network
  redis:
    container_name: tcmb_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - tcmb_network
    depends_on:
        - db

volumes:
  mysql_data:
  
networks:
  tcmb_network:
    driver: bridge 